version: '3'

services:
  web:
    build: .
    ports:
      - "11451:11451"
    volumes:
      - "./data:/app/data"  # Map the local 'data' directory to '/app/data' inside the container
      - "./upload:/app/upload"  # Map the local 'upload' directory to '/app/upload' inside the container
    image: report
    container_name: report
volumes:
  data:  # Persistent volume for the SQLite database
  upload:  # Persistent volume for uploaded files
